apiVersion: v1
kind: Service
metadata:
  name: orderbook-collector-service
  namespace: bonanza-index
  labels:
    app: orderbook-collector
spec:
  type: ClusterIP
  ports:
  - port: 6557
    targetPort: 6557
    protocol: TCP
    name: zmq-pub
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: zmq-push
  selector:
    app: orderbook-collector

