apiVersion: v1
kind: Service
metadata:
  name: telegram-log-service
  namespace: bonanza-index
  labels:
    app: telegram-log
spec:
  type: ClusterIP
  ports:
  - port: 3109
    targetPort: 3109
    protocol: TCP
    name: http
  selector:
    app: telegram-log

