apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: bonanza-index
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
  - port: 23306
    targetPort: 3306
    nodePort: 30306
    protocol: TCP
    name: mysql
  selector:
    app: mariadb

