apiVersion: v1
kind: ConfigMap
metadata:
  name: bonanza-common-config
  namespace: bonanza-index
data:
  # Redis 설정
  REDIS_HOST: "121.88.4.53"
  REDIS_PORT: "6379"
  REDIS_STORE: "SYMBOL"
  
  # QuestDB 설정
  # Service 이름 사용 (Kubernetes Service를 통한 자동 라우팅)
  QDB_HOST: "121.88.4.53"
  QDB_PORT: "30812"
  QDB_DB: "qdb"
  QDB_USER: "admin"
  QDB_ILP_HOST: "121.88.4.53"
  QDB_ILP_PORT: "30099"
  QDB_LOG: "false"
  
  # MariaDB 설정
  DB_DIALECT: "mariadb"
  DB_HOST: "121.88.4.53"
  DB_PORT: "23306"
  DB_SCHEME: "bonanza"
  
  # 공통 설정
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  
  # CORS 설정
  CORS_ORIGIN: "*"


