apiVersion: v1
kind: Service
metadata:
  name: index-calc-fe-service
  namespace: bonanza-index
  labels:
    app: index-calc-fe
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: index-calc-fe

