apiVersion: v1
kind: Service
metadata:
  name: ticker-collector-service
  namespace: bonanza-index
  labels:
    app: ticker-collector
spec:
  type: ClusterIP
  ports:
  - port: 6657
    targetPort: 6657
    protocol: TCP
    name: zmq-pub
  - port: 5657
    targetPort: 5657
    protocol: TCP
    name: zmq-push
  selector:
    app: ticker-collector

