apiVersion: v1
kind: Service
metadata:
  name: index-calculator-service
  namespace: bonanza-index
  labels:
    app: index-calculator
spec:
  type: ClusterIP
  ports:
  - port: 6757
    targetPort: 6757
    protocol: TCP
    name: zmq-pub
  selector:
    app: index-calculator

