apiVersion: v1
kind: Service
metadata:
  name: index-endpoint-service
  namespace: bonanza-index
  labels:
    app: index-endpoint
spec:
  type: ClusterIP
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  selector:
    app: index-endpoint

